# Generated by Django 4.0.4 on 2022-05-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='category',
            field=models.CharField(default='w', max_length=3),
        ),
    ]
